name: Test
on:
  push:
    branches: [ main ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Pull C++ container
        run: docker pull kbuffardi/cpp-container:latest
      - name: Test in container
        run: docker run -v $(pwd):/usr/src -t kbuffardi/cpp-container
